#!/bin/sh
# entrypoint.sh — generates creds.php from environment variables at container start,
# then hands control to the CMD (apache2-foreground).
set -e

# Require the mandatory DB credentials
if [ -z "${DB_USER}" ] || [ -z "${DB_PASS}" ]; then
    echo "ERROR: DB_USER and DB_PASS environment variables are required." >&2
    exit 1
fi

# Generate /var/www/html/creds.php from env vars
cat > /var/www/html/creds.php << PHP
<?php
// Auto-generated by entrypoint.sh — do not edit.
// Set environment variables in docker-compose.yml or .env to change these values.

\$db_host           = '${DB_HOST:-host.docker.internal}';
\$db_user           = '${DB_USER}';
\$db_pass           = '${DB_PASS}';
\$db_port           = ${DB_PORT:-3306};
\$db_name           = '${DB_NAME:-torque}';
\$db_table          = 'raw_logs';
\$db_keys_table     = 'torque_keys';
\$db_sessions_table = 'sessions';
\$torque_id         = '${TORQUE_ID:-}';
\$torque_id_hash    = '${TORQUE_ID_HASH:-}';
\$bearer_token      = '${BEARER_TOKEN:-}';

// Web login users (legacy array — new accounts should use the torque_users DB table)
\$users = [];
if (!empty('${APP_USER:-}') && !empty('${APP_PASS:-}')) {
    \$users[] = ['user' => '${APP_USER}', 'pass' => '${APP_PASS}'];
}
PHP

chown www-data:www-data /var/www/html/creds.php
chmod 600 /var/www/html/creds.php

echo "entrypoint: creds.php generated from environment variables."

# ── In-container GPS repair scheduler ─────────────────────────────────────────
# Runs gps/repair.php on an interval inside this container (no host cron needed).
# Disable with GPS_REPAIR_CRON=0; tune cadence with GPS_REPAIR_INTERVAL (seconds).
# repair.php is a no-op when GPS repair is disabled in Settings, so this is safe
# to leave on. Output is prefixed and goes to container stdout (docker logs).
if [ "${GPS_REPAIR_CRON:-1}" != "0" ]; then
    GPS_REPAIR_INTERVAL="${GPS_REPAIR_INTERVAL:-300}"
    echo "entrypoint: in-container GPS repair scheduler enabled (every ${GPS_REPAIR_INTERVAL}s)."
    (
        # Let Apache and the DB settle before the first run
        sleep 60
        while true; do
            php /var/www/html/gps/repair.php 2>&1 | sed 's/^/[gps-repair] /' || true
            sleep "${GPS_REPAIR_INTERVAL}"
        done
    ) &
else
    echo "entrypoint: in-container GPS repair scheduler disabled (GPS_REPAIR_CRON=0)."
fi

exec "$@"
