#!/bin/sh
# entrypoint.sh — generates creds.php from environment variables at container start,
# then hands control to the CMD (apache2-foreground).
set -e

# Require the mandatory DB credentials
if [ -z "${DB_USER}" ] || [ -z "${DB_PASS}" ]; then
    echo "ERROR: DB_USER and DB_PASS environment variables are required." >&2
    exit 1
fi

# Generate /var/www/html/creds.php from env vars
cat > /var/www/html/creds.php << PHP
<?php
// Auto-generated by entrypoint.sh — do not edit.
// Set environment variables in docker-compose.yml or .env to change these values.

\$db_host           = '${DB_HOST:-host.docker.internal}';
\$db_user           = '${DB_USER}';
\$db_pass           = '${DB_PASS}';
\$db_port           = ${DB_PORT:-3306};
\$db_name           = '${DB_NAME:-torque}';
\$db_table          = 'raw_logs';
\$db_keys_table     = 'torque_keys';
\$db_sessions_table = 'sessions';
\$torque_id         = '${TORQUE_ID:-}';
\$torque_id_hash    = '${TORQUE_ID_HASH:-}';

// Web login users (legacy array — new accounts should use the torque_users DB table)
\$users = [];
if (!empty('${APP_USER:-}') && !empty('${APP_PASS:-}')) {
    \$users[] = ['user' => '${APP_USER}', 'pass' => '${APP_PASS}'];
}
PHP

chown www-data:www-data /var/www/html/creds.php
chmod 600 /var/www/html/creds.php

echo "entrypoint: creds.php generated from environment variables."

exec "$@"
